#!/usr/bin/env bash

# ROOT=$(realpath "$PWD")
BIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
BIN_FILE=$(realpath "$BIN_DIR/build")
PACKAGE_DIR=$(realpath "$BIN_FILE/../..")
cd "$PACKAGE_DIR" || exit
rm -rf "./dist"
mkdir "./dist"
mkdir "./dist/assets"
mkdir "./dist/src"
tsc -p './tsconfig.json'
cp -r "./assets/" "./dist/assets"
# cd "$ROOT" || exit
# eval "node $PACKAGE_DIR/dist/src/nestdoc.js $*"

# node "$PACKAGE_DIR/dist/src/nestdoc.js" "$ARGS"
# cd "$ROOT" || exit

# ARGS=("$@")

# SCRIPT_FILE="$PACKAGE_DIR/dist/src/nestdoc.js"

# node "$SCRIPT_FILE" "$args"
