#!/usr/bin/env bash

ROOT=$PWD
echo "ROOT: $PWD"
BIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
echo "BIN_DIR: $BIN_DIR"
BIN_FILE=$(realpath "$BIN_DIR/build")
echo "BIN_FILE: $BIN_FILE"
PACKAGE_DIR=$(realpath "$BIN_FILE")
echo "PACKAGE_DIR: $PACKAGE_DIR"

# nodemon --exec "/usr/bin/bash" "$PACKAGE_DIR/scripts/build" --watch "$PACKAGE_DIR/src/*" --watch "$ROOT/src" -e js,pug,ts,css,styl,png
