#!/usr/bin/env bash

BIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
PACKAGE_DIR=$(dirname "$BIN_DIR")

bash "$BIN_DIR/build"

cd "$*" || exit

nodemon --exec "node $PACKAGE_DIR/dist/src/nestdoc -i src -o documentation --base '/api/docs' --logo 'https://leaderport.indep.pro/images/logo/logo-doc.svg'" --watch "./src/*" -e ts

# nodemon --exec "bash $SCRIPTS_DIR/build" --watch "$PACKAGE_DIR/src/*" --watch "$PACKAGE_DIR/assets/*" --watch "$ROOT/src/*" -e js,pug,ts,css,styl,png,svg -- "$*"
