#!/usr/bin/env bash

ROOT=$PWD
BIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
BIN_FILE=$(realpath "$BIN_DIR/nestdoc")
SCRIPTS_DIR=$(dirname "$BIN_FILE")
PACKAGE_DIR=$(dirname "$SCRIPTS_DIR")

nodemon --exec "bash $SCRIPTS_DIR/build" --watch "$PACKAGE_DIR/src/*" --watch "$PACKAGE_DIR/assets/*" --watch "$ROOT/src/*" -e js,pug,ts,css,styl,png,svg -- "$*"
